// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/attendance.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for checking in.
type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_proto_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// The request message for checking out. The record_id is the unique ID of the attendance record.
type CheckOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutRequest) Reset() {
	*x = CheckOutRequest{}
	mi := &file_proto_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRequest) ProtoMessage() {}

func (x *CheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRequest.ProtoReflect.Descriptor instead.
func (*CheckOutRequest) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *CheckOutRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

// The request message for getting a user's latest attendance.
type GetAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceRequest) Reset() {
	*x = GetAttendanceRequest{}
	mi := &file_proto_attendance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceRequest) ProtoMessage() {}

func (x *GetAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceRequest.ProtoReflect.Descriptor instead.
func (*GetAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{2}
}

func (x *GetAttendanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// The request message for getting all attendance records (it requires no parameters).
type GetAllAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAttendanceRequest) Reset() {
	*x = GetAllAttendanceRequest{}
	mi := &file_proto_attendance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAttendanceRequest) ProtoMessage() {}

func (x *GetAllAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAttendanceRequest.ProtoReflect.Descriptor instead.
func (*GetAllAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{3}
}

// A single attendance record response.
type AttendanceRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CheckinTime   string                 `protobuf:"bytes,4,opt,name=checkin_time,json=checkinTime,proto3" json:"checkin_time,omitempty"`
	CheckoutTime  string                 `protobuf:"bytes,5,opt,name=checkout_time,json=checkoutTime,proto3" json:"checkout_time,omitempty"`
	StatusMessage string                 `protobuf:"bytes,6,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceRecordResponse) Reset() {
	*x = AttendanceRecordResponse{}
	mi := &file_proto_attendance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceRecordResponse) ProtoMessage() {}

func (x *AttendanceRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceRecordResponse.ProtoReflect.Descriptor instead.
func (*AttendanceRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{4}
}

func (x *AttendanceRecordResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttendanceRecordResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AttendanceRecordResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AttendanceRecordResponse) GetCheckinTime() string {
	if x != nil {
		return x.CheckinTime
	}
	return ""
}

func (x *AttendanceRecordResponse) GetCheckoutTime() string {
	if x != nil {
		return x.CheckoutTime
	}
	return ""
}

func (x *AttendanceRecordResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

// The response message containing a list of all attendance records.
type GetAllAttendanceResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Records       []*AttendanceRecordResponse `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAttendanceResponse) Reset() {
	*x = GetAllAttendanceResponse{}
	mi := &file_proto_attendance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAttendanceResponse) ProtoMessage() {}

func (x *GetAllAttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAttendanceResponse.ProtoReflect.Descriptor instead.
func (*GetAllAttendanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllAttendanceResponse) GetRecords() []*AttendanceRecordResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_proto_attendance_proto protoreflect.FileDescriptor

const file_proto_attendance_proto_rawDesc = "" +
	"\n" +
	"\x16proto/attendance.proto\x12\n" +
	"attendance\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x0eCheckInRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\".\n" +
	"\x0fCheckOutRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\"/\n" +
	"\x14GetAttendanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x19\n" +
	"\x17GetAllAttendanceRequest\"\xce\x01\n" +
	"\x18AttendanceRecordResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12!\n" +
	"\fcheckin_time\x18\x04 \x01(\tR\vcheckinTime\x12#\n" +
	"\rcheckout_time\x18\x05 \x01(\tR\fcheckoutTime\x12%\n" +
	"\x0estatus_message\x18\x06 \x01(\tR\rstatusMessage\"Z\n" +
	"\x18GetAllAttendanceResponse\x12>\n" +
	"\arecords\x18\x01 \x03(\v2$.attendance.AttendanceRecordResponseR\arecords2\xde\x03\n" +
	"\x11AttendanceService\x12c\n" +
	"\aCheckIn\x12\x1a.attendance.CheckInRequest\x1a$.attendance.AttendanceRecordResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/checkin\x12r\n" +
	"\bCheckOut\x12\x1b.attendance.CheckOutRequest\x1a$.attendance.AttendanceRecordResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/checkout/{record_id}\x12y\n" +
	"\rGetAttendance\x12 .attendance.GetAttendanceRequest\x1a$.attendance.AttendanceRecordResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/attendance/{user_id}\x12u\n" +
	"\x10GetAllAttendance\x12#.attendance.GetAllAttendanceRequest\x1a$.attendance.GetAllAttendanceResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/attendanceB\x12Z\x10attendance/protob\x06proto3"

var (
	file_proto_attendance_proto_rawDescOnce sync.Once
	file_proto_attendance_proto_rawDescData []byte
)

func file_proto_attendance_proto_rawDescGZIP() []byte {
	file_proto_attendance_proto_rawDescOnce.Do(func() {
		file_proto_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_attendance_proto_rawDesc), len(file_proto_attendance_proto_rawDesc)))
	})
	return file_proto_attendance_proto_rawDescData
}

var file_proto_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_attendance_proto_goTypes = []any{
	(*CheckInRequest)(nil),           // 0: attendance.CheckInRequest
	(*CheckOutRequest)(nil),          // 1: attendance.CheckOutRequest
	(*GetAttendanceRequest)(nil),     // 2: attendance.GetAttendanceRequest
	(*GetAllAttendanceRequest)(nil),  // 3: attendance.GetAllAttendanceRequest
	(*AttendanceRecordResponse)(nil), // 4: attendance.AttendanceRecordResponse
	(*GetAllAttendanceResponse)(nil), // 5: attendance.GetAllAttendanceResponse
}
var file_proto_attendance_proto_depIdxs = []int32{
	4, // 0: attendance.GetAllAttendanceResponse.records:type_name -> attendance.AttendanceRecordResponse
	0, // 1: attendance.AttendanceService.CheckIn:input_type -> attendance.CheckInRequest
	1, // 2: attendance.AttendanceService.CheckOut:input_type -> attendance.CheckOutRequest
	2, // 3: attendance.AttendanceService.GetAttendance:input_type -> attendance.GetAttendanceRequest
	3, // 4: attendance.AttendanceService.GetAllAttendance:input_type -> attendance.GetAllAttendanceRequest
	4, // 5: attendance.AttendanceService.CheckIn:output_type -> attendance.AttendanceRecordResponse
	4, // 6: attendance.AttendanceService.CheckOut:output_type -> attendance.AttendanceRecordResponse
	4, // 7: attendance.AttendanceService.GetAttendance:output_type -> attendance.AttendanceRecordResponse
	5, // 8: attendance.AttendanceService.GetAllAttendance:output_type -> attendance.GetAllAttendanceResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_attendance_proto_init() }
func file_proto_attendance_proto_init() {
	if File_proto_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_attendance_proto_rawDesc), len(file_proto_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_attendance_proto_goTypes,
		DependencyIndexes: file_proto_attendance_proto_depIdxs,
		MessageInfos:      file_proto_attendance_proto_msgTypes,
	}.Build()
	File_proto_attendance_proto = out.File
	file_proto_attendance_proto_goTypes = nil
	file_proto_attendance_proto_depIdxs = nil
}
