apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: attendance-mongo
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: attendance-mongo
    release: {{ .Release.Name }}
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
